apiVersion: apps/v1
kind: Deployment
metadata:
  name: double-decker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: double-decker
  template:
    metadata:
      labels:
        app: double-decker
    spec:
      containers:
        - name: app
          image: <YOUR_DOCKER_IMAGE>
          ports:
            - containerPort: 8080
